apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mg90vdlld-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mg90vdlld-go 
  name: mg90vdlld-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mg90vdlld-go 
